---
all:
  vars:
    ansible_user: centos
    ansible_private_key_file: "/home/ssharma/Downloads/sunita_field.pem"
  hosts: 
    ## 2xlarge/100gb vol for worker node#1
    3.94.167.42:
      ansible_host: 3.94.167.42

      private_hostname: ip-172-31-16-186.ec2.internal
      private_ip: 172.31.16.186
      public_hostname: ec2-3-94-167-42.compute-1.amazonaws.com
      public_ip: 3.94.167.42

    ## 2xlarge/100gb vol for worker node#2
    52.90.154.199:
      ansible_host: 52.90.154.199

      private_hostname: ip-172-31-18-35.ec2.internal
      private_ip: 172.31.18.35
      public_hostname: ec2-52-90-154-199.compute-1.amazonaws.com
      public_ip: 52.90.154.199
  
    ## 2xlarge/100gb vol for worker node#3
    54.208.14.90:
      ansible_host: 54.208.14.90

      private_hostname: ip-172-31-31-217.ec2.internal
      private_ip: 172.31.31.217
      public_hostname: ec2-54-208-14-90.compute-1.amazonaws.com
      public_ip:  54.208.14.90

    # 2XLAGE /100gb for CDF node
    54.85.168.49:
      ansible_host: 54.85.168.49

      private_hostname: ip-172-31-23-106.ec2.internal
      private_ip: 172.31.23.106
      public_hostname: ec2-54-85-168-49.compute-1.amazonaws.com
      public_ip: 54.85.168.49
    
    # 4xlarge/100mb for CDSW node
    100.24.8.58:
      ansible_host: 100.24.8.58

      private_hostname: ip-172-31-17-166.ec2.internal
      private_ip: 172.31.17.166
      public_hostname: ec2-100-24-8-58.compute-1.amazonaws.com
      public_ip: 100.24.8.58

    # 4xlarge/100mg for main_master
    54.91.49.29:
      ansible_host: 54.91.49.29

      private_hostname: ip-172-31-28-8.ec2.internal
      private_ip: 172.31.28.8
      public_hostname: ec2-54-91-49-29.compute-1.amazonaws.com
      public_ip: 54.91.49.29
    
#    54.82.57.181:
#      ansible_host: 54.82.57.181
#
#      private_hostname: ip-172-31-24-65.ec2.internal
#      private_ip: 172.31.24.65
#      public_hostname: ec2-54-82-57-181.compute-1.amazonaws.com
#      public_ip: 54.82.57.181

  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    cm_server:
      hosts:
        54.91.49.29:
    db_server:
      hosts:
        54.91.49.29:
    main_master:
      hosts:
        54.91.49.29:

    krb5_server:
      hosts:
        54.91.49.29:
        
    workers:
      hosts:
        3.94.167.42:
        52.90.154.199:
        54.208.14.90:
    
    cdf:
      hosts:
        54.85.168.49:

    cdsw_master:
      hosts:
        100.24.8.58:

    cdpdc:
      children:
        main_master:
        db_server:
        cm_server:
        masters:
        workers:
        cdf:
        cdsw_master:
